apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ci-rs
  namespace: test
  labels:
    app: ci-server
    env: dev
    tier: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: ci
  template:
    metadata:
      name: jenkins
      namespace: test
      labels:
        tier: ci
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:jdk11
        ports:
        - containerPort: 8080
