apiVersion: v1
kind: Pod

metadata:
  name: mysql-pod
  labels:
    app: mysql
    tier: final

spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: DATABASE_NAME
      valueFrom:
        configMapKeyRef:
          name: app-configs
          key: mysql_db_name
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: mysql_password

